blank_issues_enabled: false
contact_links:
  - name: çœŸAIå¥èº«ä¿±ä¹éƒ¨ ğŸ’ªğŸ»
    url: https://bkzbhyrhgv.feishu.cn/docx/GuNMdGVOgotw3lxQPUFcDpgTnKg
    about: å¦‚æœä½ æƒ³å­¦ä¹ å®è·µAIï¼Œå¹¶å¯¹å¥èº«æ„Ÿå…´è¶£ï¼Œæ¬¢è¿åŠ å…¥ã€ŒçœŸAIå¥èº«ä¿±ä¹éƒ¨ã€
